// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2mzowR-C1XCunTFhO8AnNtwkpLXS-ytw',
    appId: '1:442507371698:android:37bbbd8ba83e4f0866d5ab',
    messagingSenderId: '442507371698',
    projectId: 'flutter-6d387',
    storageBucket: 'flutter-6d387.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI_sgLpdqx4i6bZtxx5uEXvY8QRz0zCSM',
    appId: '1:442507371698:ios:5f377e38c6bba66666d5ab',
    messagingSenderId: '442507371698',
    projectId: 'flutter-6d387',
    storageBucket: 'flutter-6d387.appspot.com',
    androidClientId: '442507371698-qncroihbi26iacocbdvbsgjr8d1hlp9g.apps.googleusercontent.com',
    iosClientId: '442507371698-rh9m22ammvcgss55d9ob9anp9esbubti.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
